source 'http://rubygems.org'

# Source: https://github.com/jlong/serve
gem "serve", ">= 1.0.0"

gem 'haml'
gem 'compass'
gem 'html5-boilerplate' , :require => 'html5-boilerplate/app/helpers/html5_boilerplate_helper'
gem 'slim', :require => 'slim/rails'

gem "maruku", ">= 0.6.0"

gem 'i18n'
